/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sandoval.form;

import com.sandoval.model.beans.Produto;
import com.sandoval.model.dao.ProdutoDao;
import java.awt.Color;



/**
 *
 * @author Sandoval
 */
public class CadastroProduto extends javax.swing.JPanel {

    /**
     * Creates new form Form1
     */
    public CadastroProduto() {
        initComponents();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.sandoval.swing.PanelBorder();
        titulo = new javax.swing.JLabel();
        nomeGenerico = new javax.swing.JLabel();
        txtNomeGenerico = new javax.swing.JTextField();
        separadorDois = new javax.swing.JSeparator();
        tarja = new javax.swing.JLabel();
        cbmTarja = new javax.swing.JComboBox<>();
        fabricante = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        separadorQuinto = new javax.swing.JSeparator();
        formaConsumo = new javax.swing.JLabel();
        cbmConsumo = new javax.swing.JComboBox<>();
        separadorSeis = new javax.swing.JSeparator();
        nomeGenerico1 = new javax.swing.JLabel();
        separadorSeis1 = new javax.swing.JSeparator();
        txtNomeComercial = new javax.swing.JTextField();
        separadorDois1 = new javax.swing.JSeparator();
        panelBorder2 = new com.sandoval.swing.PanelBorder();
        cadastrar = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        separadorSeis2 = new javax.swing.JSeparator();
        txfValor = new javax.swing.JFormattedTextField();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setPreferredSize(new java.awt.Dimension(870, 571));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(127, 127, 127));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CADASTRO DE PRODUTOS");
        panelBorder1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 23, -1, 37));

        nomeGenerico.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nomeGenerico.setText("Nome generico (quimico):");
        panelBorder1.add(nomeGenerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        txtNomeGenerico.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtNomeGenerico.setForeground(new java.awt.Color(204, 204, 204));
        txtNomeGenerico.setText("Nome generico do produto");
        txtNomeGenerico.setBorder(null);
        txtNomeGenerico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeGenericoMouseClicked(evt);
            }
        });
        panelBorder1.add(txtNomeGenerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 326, 29));

        separadorDois.setForeground(new java.awt.Color(153, 153, 153));
        panelBorder1.add(separadorDois, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 323, 12));

        tarja.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tarja.setText("Tarja:");
        panelBorder1.add(tarja, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        cbmTarja.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cbmTarja.setForeground(new java.awt.Color(204, 204, 204));
        cbmTarja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarja amarela", "Tarja vermelha", "Tarja Preta" }));
        cbmTarja.setBorder(null);
        panelBorder1.add(cbmTarja, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 170, 32));

        fabricante.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        fabricante.setText("Fabricante:");
        panelBorder1.add(fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 30));

        txtFabricante.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtFabricante.setForeground(new java.awt.Color(204, 204, 204));
        txtFabricante.setText("Fabricante do produto");
        txtFabricante.setBorder(null);
        txtFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFabricanteMouseClicked(evt);
            }
        });
        panelBorder1.add(txtFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 323, 32));

        separadorQuinto.setForeground(new java.awt.Color(153, 153, 153));
        panelBorder1.add(separadorQuinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 323, 18));

        formaConsumo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        formaConsumo.setText("Forma de consumo:");
        panelBorder1.add(formaConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        cbmConsumo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cbmConsumo.setForeground(new java.awt.Color(204, 204, 204));
        cbmConsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Via oral", "Sublingual", "Forma liquida" }));
        cbmConsumo.setBorder(null);
        panelBorder1.add(cbmConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 170, 32));

        separadorSeis.setForeground(new java.awt.Color(153, 153, 153));
        panelBorder1.add(separadorSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 322, 16));

        nomeGenerico1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nomeGenerico1.setText("Nome Comercial:");
        panelBorder1.add(nomeGenerico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        separadorSeis1.setForeground(new java.awt.Color(153, 153, 153));
        panelBorder1.add(separadorSeis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 340, 16));

        txtNomeComercial.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtNomeComercial.setForeground(new java.awt.Color(204, 204, 204));
        txtNomeComercial.setText("Nome comercial do produto");
        txtNomeComercial.setBorder(null);
        txtNomeComercial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeComercialMouseClicked(evt);
            }
        });
        panelBorder1.add(txtNomeComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 336, 29));

        separadorDois1.setForeground(new java.awt.Color(153, 153, 153));
        panelBorder1.add(separadorDois1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 336, 12));

        panelBorder2.setBackground(new java.awt.Color(163, 193, 219));

        cadastrar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrar.setText("CADASTRAR");
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelBorder1.add(panelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 480, -1, -1));

        valor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        valor.setText("Valor:");
        panelBorder1.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        separadorSeis2.setForeground(new java.awt.Color(153, 153, 153));
        panelBorder1.add(separadorSeis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 340, 16));

        txfValor.setBorder(null);
        txfValor.setForeground(new java.awt.Color(204, 204, 204));
        try {
            txfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfValor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txfValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfValorMouseClicked(evt);
            }
        });
        panelBorder1.add(txfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 340, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeGenericoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeGenericoMouseClicked
        if(txtNomeGenerico.getText().equals("Nome generico do produto")) {
           txtNomeGenerico.setText("");
           txtNomeGenerico.setForeground(Color.black); 
        }
    }//GEN-LAST:event_txtNomeGenericoMouseClicked

    private void txtNomeComercialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeComercialMouseClicked
        if(txtNomeComercial.getText().equals("Nome comercial do produto")) {
           txtNomeComercial.setText("");
           txtNomeComercial.setForeground(Color.black); 
        }
    }//GEN-LAST:event_txtNomeComercialMouseClicked

    private void txtFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFabricanteMouseClicked
        if(txtFabricante.getText().equals("Fabricante do produto")) {
           txtFabricante.setText("");
           txtFabricante.setForeground(Color.black); 
           
           
        }
    }//GEN-LAST:event_txtFabricanteMouseClicked

    private void txfValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfValorMouseClicked
        if(txfValor.getText().equals("  /  /    ")) {
            txfValor.setText("");
            txfValor.setForeground(Color.black);
        }
    }//GEN-LAST:event_txfValorMouseClicked

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        
        Produto produto = new Produto();
        ProdutoDao dao = new ProdutoDao();
        
        produto.setGenerico(txtNomeGenerico.getText());
        produto.setComercial(txtNomeComercial.getText());
        produto.setFabricante(txtFabricante.getText());
        produto.setValor(txfValor.getText());
        produto.setConsumo(cbmConsumo.getItemAt(cbmConsumo.getSelectedIndex()));
        produto.setTarja(cbmTarja.getItemAt(cbmTarja.getSelectedIndex()));
        
        dao.create(produto);
        
    }//GEN-LAST:event_cadastrarMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastrar;
    private javax.swing.JComboBox<String> cbmConsumo;
    private javax.swing.JComboBox<String> cbmTarja;
    private javax.swing.JLabel fabricante;
    private javax.swing.JLabel formaConsumo;
    private javax.swing.JLabel nomeGenerico;
    private javax.swing.JLabel nomeGenerico1;
    private com.sandoval.swing.PanelBorder panelBorder1;
    private com.sandoval.swing.PanelBorder panelBorder2;
    private javax.swing.JSeparator separadorDois;
    private javax.swing.JSeparator separadorDois1;
    private javax.swing.JSeparator separadorQuinto;
    private javax.swing.JSeparator separadorSeis;
    private javax.swing.JSeparator separadorSeis1;
    private javax.swing.JSeparator separadorSeis2;
    private javax.swing.JLabel tarja;
    private javax.swing.JLabel titulo;
    private javax.swing.JFormattedTextField txfValor;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtNomeComercial;
    private javax.swing.JTextField txtNomeGenerico;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
