/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sandoval.form;

import com.sandoval.model.ModelCard;
import javax.swing.ImageIcon;

/**
 *
 * @author Sandoval
 */
public class Relatorio extends javax.swing.JPanel {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        
        card1.setData(new ModelCard(new ImageIcon(getClass().getResource("/com/sandoval/icon/relatorioicon.png")), "Diario", "R$200", " "));
        card2.setData(new ModelCard(new ImageIcon(getClass().getResource("/com/sandoval/icon/relatorioicon.png")), "Semanal", "R$1500", " "));
        card6.setData(new ModelCard(new ImageIcon(getClass().getResource("/com/sandoval/icon/relatorioicon.png")), "Mensal", "R$3000", " "));
        card7.setData(new ModelCard(new ImageIcon(getClass().getResource("/com/sandoval/icon/relatorioicon.png")), "Anual", "R$600000", " "));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.sandoval.swing.PanelBorder();
        titulo = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        card1 = new com.sandoval.component.Card();
        card2 = new com.sandoval.component.Card();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        card6 = new com.sandoval.component.Card();
        card7 = new com.sandoval.component.Card();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setPreferredSize(new java.awt.Dimension(870, 571));

        titulo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(127, 127, 127));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("RELATORIO");

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        card1.setAutoscrolls(true);
        card1.setColor1(new java.awt.Color(70, 130, 180));
        card1.setColor2(new java.awt.Color(135, 206, 235));
        jLayeredPane1.add(card1);

        card2.setColor1(new java.awt.Color(70, 130, 180));
        card2.setColor2(new java.awt.Color(135, 206, 235));
        jLayeredPane1.add(card2);

        jLayeredPane2.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        card6.setColor1(new java.awt.Color(70, 130, 180));
        card6.setColor2(new java.awt.Color(135, 206, 235));
        jLayeredPane2.add(card6);

        card7.setColor1(new java.awt.Color(70, 130, 180));
        card7.setColor2(new java.awt.Color(135, 206, 235));
        jLayeredPane2.add(card7);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sandoval.component.Card card1;
    private com.sandoval.component.Card card2;
    private com.sandoval.component.Card card6;
    private com.sandoval.component.Card card7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private com.sandoval.swing.PanelBorder panelBorder1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
