/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sandoval.form;

import java.awt.Color;

/**
 *
 * @author Sandoval
 */
public class Vendas extends javax.swing.JPanel {

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.sandoval.swing.PanelBorder();
        titulo = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        separadorUm = new javax.swing.JSeparator();
        produto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        separadorDois = new javax.swing.JSeparator();
        quantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        separadorUm1 = new javax.swing.JSeparator();
        tarja = new javax.swing.JLabel();
        cbmTarja = new javax.swing.JComboBox<>();
        separadorSeis1 = new javax.swing.JSeparator();
        fabricante = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        separadorQuinto = new javax.swing.JSeparator();
        panelBorder2 = new com.sandoval.swing.PanelBorder();
        quantidadeFinal = new javax.swing.JLabel();
        produtoFinal = new javax.swing.JLabel();
        txtProdutoFinal = new javax.swing.JTextField();
        txtQuantidadeFinal = new javax.swing.JTextField();
        separadorDois1 = new javax.swing.JSeparator();
        separadorDois2 = new javax.swing.JSeparator();
        tituloDemonstrativo = new javax.swing.JLabel();
        panelBorder3 = new com.sandoval.swing.PanelBorder();
        valor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        panelBorder4 = new com.sandoval.swing.PanelBorder();
        cadastrarVenda = new javax.swing.JLabel();
        panelBorder5 = new com.sandoval.swing.PanelBorder();
        excluir = new javax.swing.JLabel();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setPreferredSize(new java.awt.Dimension(870, 571));

        titulo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(127, 127, 127));
        titulo.setText("VENDAS");

        id.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        id.setText("ID:");

        txtId.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(204, 204, 204));
        txtId.setText("ID do produto");
        txtId.setBorder(null);
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
        });

        separadorUm.setForeground(new java.awt.Color(153, 153, 153));

        produto.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        produto.setText("Produto");

        txtProduto.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtProduto.setForeground(new java.awt.Color(204, 204, 204));
        txtProduto.setText("Nome do produto");
        txtProduto.setBorder(null);
        txtProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProdutoMouseClicked(evt);
            }
        });

        separadorDois.setForeground(new java.awt.Color(153, 153, 153));

        quantidade.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        quantidade.setText("Quantidade");

        txtQuantidade.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(204, 204, 204));
        txtQuantidade.setText("Quantidade do produto");
        txtQuantidade.setBorder(null);
        txtQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuantidadeMouseClicked(evt);
            }
        });

        separadorUm1.setForeground(new java.awt.Color(153, 153, 153));

        tarja.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tarja.setText("Tarja:");

        cbmTarja.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cbmTarja.setForeground(new java.awt.Color(204, 204, 204));
        cbmTarja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarja amarela", "Tarja vermelha", "Tarja Preta" }));
        cbmTarja.setBorder(null);

        separadorSeis1.setForeground(new java.awt.Color(153, 153, 153));

        fabricante.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        fabricante.setText("Fabricante:");

        txtFabricante.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtFabricante.setForeground(new java.awt.Color(204, 204, 204));
        txtFabricante.setText("Fabricante do produto");
        txtFabricante.setBorder(null);
        txtFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFabricanteMouseClicked(evt);
            }
        });

        separadorQuinto.setForeground(new java.awt.Color(153, 153, 153));

        panelBorder2.setBackground(new java.awt.Color(163, 193, 219));

        quantidadeFinal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        quantidadeFinal.setText("Quantidade");

        produtoFinal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        produtoFinal.setText("Produto");

        txtProdutoFinal.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtProdutoFinal.setForeground(new java.awt.Color(204, 204, 204));
        txtProdutoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProdutoFinal.setText("Total de produtos");
        txtProdutoFinal.setToolTipText("");
        txtProdutoFinal.setBorder(null);
        txtProdutoFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProdutoFinalMouseClicked(evt);
            }
        });

        txtQuantidadeFinal.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtQuantidadeFinal.setForeground(new java.awt.Color(204, 204, 204));
        txtQuantidadeFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantidadeFinal.setText("Quantidade total");
        txtQuantidadeFinal.setBorder(null);
        txtQuantidadeFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuantidadeFinalMouseClicked(evt);
            }
        });

        separadorDois1.setForeground(new java.awt.Color(153, 153, 153));

        separadorDois2.setForeground(new java.awt.Color(153, 153, 153));

        tituloDemonstrativo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tituloDemonstrativo.setForeground(new java.awt.Color(127, 127, 127));
        tituloDemonstrativo.setText("DEMONSTRATIVO");

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));

        valor.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor.setText("Valor:");

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(valor)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder3Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(valor)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        txtValor.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtValor.setForeground(new java.awt.Color(204, 204, 204));
        txtValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor.setText("VALOR FINAL");
        txtValor.setBorder(null);
        txtValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder2Layout.createSequentialGroup()
                                .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(separadorDois2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(separadorDois1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(produtoFinal)
                            .addComponent(txtProdutoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantidadeFinal)
                    .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                            .addComponent(txtQuantidadeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                            .addComponent(tituloDemonstrativo)
                            .addGap(69, 69, 69)))))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tituloDemonstrativo)
                .addGap(18, 18, 18)
                .addComponent(produtoFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProdutoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separadorDois1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQuantidadeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorDois2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelBorder4.setBackground(new java.awt.Color(163, 193, 219));

        cadastrarVenda.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cadastrarVenda.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarVenda.setText("CADASTRAR VENDA");
        cadastrarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelBorder4Layout = new javax.swing.GroupLayout(panelBorder4);
        panelBorder4.setLayout(panelBorder4Layout);
        panelBorder4Layout.setHorizontalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrarVenda)
                    .addGap(91, 91, 91)))
        );
        panelBorder4Layout.setVerticalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cadastrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelBorder5.setBackground(new java.awt.Color(163, 193, 219));

        excluir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        excluir.setForeground(new java.awt.Color(255, 255, 255));
        excluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        excluir.setText("EXCLUIR");
        excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelBorder5Layout = new javax.swing.GroupLayout(panelBorder5);
        panelBorder5.setLayout(panelBorder5Layout);
        panelBorder5Layout.setHorizontalGroup(
            panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder5Layout.setVerticalGroup(
            panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separadorQuinto)
                            .addComponent(txtFabricante))
                        .addGap(53, 53, 53))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fabricante)
                            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(produto)
                                .addComponent(separadorUm)
                                .addComponent(id)
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(separadorDois))
                            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(separadorUm1)
                                .addComponent(quantidade)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(tarja)
                                .addComponent(separadorSeis1)
                                .addComponent(cbmTarja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)))
                .addGap(34, 34, 34)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(panelBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBorder5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(367, 367, 367))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(produto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(separadorDois, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(separadorUm, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(separadorUm1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbmTarja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separadorSeis1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separadorQuinto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBorder5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
        if(txtId.getText().equals("ID do produto")) {
            txtId.setText("");
            txtId.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtIdMouseClicked

    private void txtProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProdutoMouseClicked
        if(txtProduto.getText().equals("Nome do produto")) {
            txtProduto.setText("");
            txtProduto.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtProdutoMouseClicked

    private void txtQuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuantidadeMouseClicked
        if(txtQuantidade.getText().equals("Quantidade do produto")) {
            txtQuantidade.setText("");
            txtQuantidade.setForeground(Color.black);

        }
    }//GEN-LAST:event_txtQuantidadeMouseClicked

    private void txtFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFabricanteMouseClicked
        if(txtFabricante.getText().equals("Fabricante do produto")) {
            txtFabricante.setText("");
            txtFabricante.setForeground(Color.black);

        }
    }//GEN-LAST:event_txtFabricanteMouseClicked

    private void txtQuantidadeFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuantidadeFinalMouseClicked
        if(txtQuantidadeFinal.getText().equals("Quantidade total")) {
            txtQuantidadeFinal.setText("");
            txtQuantidadeFinal.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtQuantidadeFinalMouseClicked

    private void txtProdutoFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProdutoFinalMouseClicked
        if(txtProdutoFinal.getText().equals("Total de produtos")) {
            txtProdutoFinal.setText("");
            txtProdutoFinal.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtProdutoFinalMouseClicked

    private void txtValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorMouseClicked
        if(txtValor.getText().equals("VALOR FINAL")) {
            txtValor.setText("");
            txtValor.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtValorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastrarVenda;
    private javax.swing.JComboBox<String> cbmTarja;
    private javax.swing.JLabel excluir;
    private javax.swing.JLabel fabricante;
    private javax.swing.JLabel id;
    private com.sandoval.swing.PanelBorder panelBorder1;
    private com.sandoval.swing.PanelBorder panelBorder2;
    private com.sandoval.swing.PanelBorder panelBorder3;
    private com.sandoval.swing.PanelBorder panelBorder4;
    private com.sandoval.swing.PanelBorder panelBorder5;
    private javax.swing.JLabel produto;
    private javax.swing.JLabel produtoFinal;
    private javax.swing.JLabel quantidade;
    private javax.swing.JLabel quantidadeFinal;
    private javax.swing.JSeparator separadorDois;
    private javax.swing.JSeparator separadorDois1;
    private javax.swing.JSeparator separadorDois2;
    private javax.swing.JSeparator separadorQuinto;
    private javax.swing.JSeparator separadorSeis1;
    private javax.swing.JSeparator separadorUm;
    private javax.swing.JSeparator separadorUm1;
    private javax.swing.JLabel tarja;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloDemonstrativo;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtProdutoFinal;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtQuantidadeFinal;
    private javax.swing.JTextField txtValor;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
